// Builds the site's first-party scripts (SPEC 36) from server/static/client into
// server/static/site.gen.ts, which the Worker and Node both serve without reading files:
//   sky.{hash}.js    synchronous, in <head>: the hour, the moon and html.js (at most 1 KB)
//   site.{hash}.js   the module that brings the meadow to life, with core/names.ts swapped for a
//                    late-bound stub (the name generator is big and only fusion needs it);
//                    offline species generation is disabled because the page provides its frozen forms
//   names.{hash}.js  the real fusion names, imported on the first fuse
// esbuild comes from wrangler's own dependency, so wrangler stays the only dev dependency (SPEC 12).
//   node server/static/build.ts            write site.gen.ts
//   node server/static/build.ts --watch    rebuild on every change under server/static/client
import { createHash } from 'node:crypto'
import { watch, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url))
const require = createRequire(import.meta.url)
type Esbuild = typeof import('esbuild')
const esbuild = createRequire(require.resolve('wrangler/package.json'))('esbuild') as Esbuild

export const OUT = here('./site.gen.ts')
const hash = (s: string) => createHash('sha256').update(s).digest('hex').slice(0, 10)

/** The pixel font's glyphs, read from png.ts once here, so site.js needs no PNG code. */
async function glyphTable(): Promise<string> {
  const { glyph } = await import('../src/pages-font.ts')
  const chars = [...Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)), '·', '…']
  return JSON.stringify(chars.map(ch => glyph(ch).map(m => m.toString(32)).join('')).join(''))
}

type BundleOptions = { format: 'iife' | 'esm'; stubNames?: boolean; define?: Record<string, string>; split?: boolean }

/**
 * One entry, bundled and minified. With `split`, the sections site.js loads later (import()) come out
 * as their own `part.{hash}.js` files beside it, imported by relative path from /static/.
 */
async function build(entry: string, o: BundleOptions): Promise<{ main: string; parts: Record<string, string> }> {
  const res = await esbuild.build({
    entryPoints: { main: here(entry) }, bundle: true, write: false, minify: true, format: o.format, target: 'es2022', platform: 'browser',
    legalComments: 'none', charset: 'utf8', define: o.define ?? {}, logLevel: 'silent',
    ...(o.split ? { splitting: true, outdir: here('./.parts'), entryNames: '[name]', chunkNames: 'part.[hash]' } : {}),
    plugins: o.stubNames ? [{
      name: 'names-stub',
      setup(b) {
        b.onResolve({ filter: /[\\/]names\.ts$/ }, args => (/core[\\/]naming\.ts$/.test(args.importer) ? { path: here('./client/names-stub.ts') } : undefined))
        b.onResolve({ filter: /[\\/]generators[\\/]index\.ts$/ }, () => ({ path: here('./client/generators-stub.ts') }))
        b.onResolve({ filter: /[\\/]png\.ts$/ }, args => (/pages-font\.ts$/.test(args.importer) ? { path: here('./client/png-glyphs.ts') } : undefined))
      },
    }] : [],
  })
  const out = res.outputFiles.map(f => ({ name: f.path.replace(/^.*[\\/]/, ''), text: f.text.replace(/\n$/, '') }))
  const main = out.find(f => !o.split || f.name === 'main.js')!
  return { main: main.text, parts: Object.fromEntries(out.filter(f => f !== main).map(f => [f.name, f.text])) }
}

const bundle = async (entry: string, o: BundleOptions) => (await build(entry, o)).main

/** Every script, built fresh, as the text of site.gen.ts. */
export async function buildSite(): Promise<string> {
  const sky = await bundle('./client/sky.ts', { format: 'iife' })
  const names = await bundle('./client/names-chunk.ts', { format: 'esm' })
  const files = { sky: `sky.${hash(sky)}.js`, names: `names.${hash(names)}.js`, site: '' }
  const built = await build('./client/site.ts', { format: 'esm', stubNames: true, split: true, define: { __NAMES_URL__: JSON.stringify(`/static/${files.names}`), __GLYPHS__: await glyphTable() } })
  const site = built.main
  files.site = `site.${hash(site)}.js`
  const parts = Object.keys(built.parts).sort()
  return `// Generated by server/static/build.ts from server/static/client. Do not edit: run \`node server/static/build.ts\`.
export const SITE_ASSETS = ${JSON.stringify(files)} as const
export const SKY_JS = ${JSON.stringify(sky)}
export const SITE_JS = ${JSON.stringify(site)}
export const NAMES_JS = ${JSON.stringify(names)}
/** The parts site.js loads later: the battle engine, the den and the code they share. */
export const SITE_PARTS: Record<string, string> = {
${parts.map(p => `  ${JSON.stringify(p)}: ${JSON.stringify(built.parts[p])},`).join('\n')}
}
export const SITE_FILES: Record<string, string> = { [SITE_ASSETS.sky]: SKY_JS, [SITE_ASSETS.site]: SITE_JS, [SITE_ASSETS.names]: NAMES_JS, ...SITE_PARTS }
`
}

async function write() {
  const t = Date.now()
  try {
    const out = await buildSite()
    writeFileSync(OUT, out)
    console.log(`site.gen.ts written (${out.length} bytes) in ${Date.now() - t} ms`)
  } catch (e) {
    console.error(e instanceof Error ? e.message : e)
    if (!process.argv.includes('--watch')) process.exitCode = 1
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url).toLowerCase() === (await import('node:path')).resolve(process.argv[1]).toLowerCase()) {
  await write()
  if (process.argv.includes('--watch')) {
    let timer: ReturnType<typeof setTimeout> | undefined
    const again = () => { clearTimeout(timer); timer = setTimeout(write, 120) }
    watch(here('./client'), { recursive: true }, again)
    for (const f of ['pages-meet.ts', 'pages-sprite.ts', 'pages-font.ts']) watch(here(`../src/${f}`), again)
    console.log('watching server/static/client')
  }
}
