import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { describe, it } from 'node:test'
import { ECONOMY } from '../../plugin/hooks/core/economy.ts'
import { FAMILY_INFO } from '../../plugin/hooks/core/families.ts'
import { GENERATOR_VERSIONS, generateSeason } from '../../plugin/hooks/core/generators/index.ts'
import { generateSeasonV2 } from '../../plugin/hooks/core/generators/v2.ts'
import { BLOCKED_WORDS } from '../../plugin/hooks/core/naming.ts'
import { STAGE_SHAPE } from '../../plugin/hooks/core/names.ts'
import { GENERATOR_VERSION } from '../../plugin/hooks/core/species.ts'

// Complete JSON bytes captured from the released v0.2.2 species generator, before extraction.
const HASHES: Record<string, string> = {
  1: 'b1fa5fcce3f429664b53052f7f8c581ee0ec8d3452757394fc3f1d0f099ef440',
  2: 'a194b8902a024c33832296bc568ea0cf7633fe7a20f733eb9b6d6cb27230ee2c',
  9: 'bdf7055d366d46b5d9e1d42c52cb1c7a071fc099f8ec57d4c7d40924bc35caa4',
  10: '9b3ea4689b2e188414064321565abb630fb292c960fe5f23999f05b15c1540ed',
  13: '834d26832704aea63b4d3208199f56f9f0d633930a01298b5ee050aaaad43a45',
  32: '21cdaa8be5643241eee5cfc1a12217c007ffde9910711fbe05c740664d8b0e37',
  99: 'a7df5d164c3f58a1fc8cbdf50ffcce1d249de8a9605cdf0b1392a4297208f23c',
  100: '3c52eac40d90f8e0d8866d0c0a6bfcd3e691a5de1da2f55720f1561ca2e87d98',
}
const hash = (value: unknown) => createHash('sha256').update(JSON.stringify(value)).digest('hex')

describe('retained species generators', () => {
  it('keeps every generated byte of released generator 2 across season and naming-rotation boundaries', () => {
    for (const [season, expected] of Object.entries(HASHES)) {
      const forms = generateSeason(Number(season), 2)
      assert.equal(hash(forms), expected, `season ${season}`)
      assert.equal(forms.length, 36)
    }
  })

  it('keeps old output independent of changes to the current families, stat tuning and name rules', () => {
    const economy = ECONOMY as unknown as { stats: { jitter: number; legendaryBase: number } }
    const bias = FAMILY_INFO.haiku.bias
    const hue = FAMILY_INFO.opus.hue
    const shape = STAGE_SHAPE[1]
    const blocked = BLOCKED_WORDS as string[]
    const previous = { jitter: economy.stats.jitter, legendary: economy.stats.legendaryBase, hp: bias.hp, hue: [...hue], letters: [...shape.letters], blocked: blocked.length }
    try {
      economy.stats.jitter = 0
      economy.stats.legendaryBase = 9
      bias.hp = 999
      hue[0] = 0
      hue[1] = 1
      ;(shape.letters as number[])[0] = 40
      ;(shape.letters as number[])[1] = 48
      blocked.push('leaf', 'moss', 'coal')
      assert.equal(hash(generateSeasonV2(100)), HASHES[100])
    } finally {
      economy.stats.jitter = previous.jitter
      economy.stats.legendaryBase = previous.legendary
      bias.hp = previous.hp
      hue[0] = previous.hue[0]!
      hue[1] = previous.hue[1]!
      ;(shape.letters as number[])[0] = previous.letters[0]!
      ;(shape.letters as number[])[1] = previous.letters[1]!
      blocked.length = previous.blocked
    }
  })

  it('returns independent forms without exposing its cached name rotation', () => {
    const forms = generateSeason(1, 2)
    forms[0]!.names[0] = 'Changed'
    forms[0]!.base.hp = 999
    forms[0]!.hue = 0
    forms.pop()
    assert.equal(hash(generateSeason(1, 2)), HASHES[1])
  })

  it('rejects unsupported versions and invalid season bounds without guessing or resetting', () => {
    assert.ok(GENERATOR_VERSIONS.includes(2), 'released generator 2 remains registered')
    assert.ok(GENERATOR_VERSIONS.includes(GENERATOR_VERSION), 'the current generator has an implementation')
    assert.equal(new Set(GENERATOR_VERSIONS).size, GENERATOR_VERSIONS.length)
    assert.ok(Object.isFrozen(GENERATOR_VERSIONS))
    for (const version of [0, -1, Math.max(...GENERATOR_VERSIONS) + 1, NaN, Infinity]) assert.throws(() => generateSeason(1, version), RangeError)
    for (const season of [0, -1, 1.5, 10000, NaN, Infinity]) assert.throws(() => generateSeason(season, 2), RangeError)
  })

  it('imports only the versioned naming helper and types, with no current naming, family, economy or RNG dependency', () => {
    const paths = ['v2.ts', 'v2-names.ts']
    for (const path of paths) {
      const source = readFileSync(new URL(`../../plugin/hooks/core/generators/${path}`, import.meta.url), 'utf8')
      const imports = [...source.matchAll(/^import (?!type\b)[^\n]+ from '([^']+)'/gm)].map(m => m[1])
      assert.deepEqual(imports, path === 'v2.ts' ? ['./v2-names.ts'] : [])
      assert.doesNotMatch(source, /\bimport\s*\(|\bDate\.now\(|\bMath\.random\(|\bfetch\(|\bprocess\./)
    }
  })
})
