// Embed the four local backgrounds for hosts that render SVG images without filesystem access.
import { readFileSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'

const families = ['haiku', 'sonnet', 'opus', 'fable'] as const
const root = new URL('../', import.meta.url)
const entries = families.map(family => {
  const bytes = readFileSync(new URL(`art/arenas/${family}.png`, root))
  if (!bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) || bytes.length > 36 * 1024) throw new Error('Invalid arena artwork')
  const sha256 = createHash('sha256').update(bytes).digest('hex')
  console.log(`${family}: ${bytes.length} bytes, sha256 ${sha256}`)
  const chunks = bytes.toString('base64').match(/.{1,96}/g)!
  return `  // ${family}.png: ${bytes.length} bytes; sha256 ${sha256}\n  ${family}: [\n    ${JSON.stringify('data:image/png;base64,')},\n${chunks.map(chunk => `    ${JSON.stringify(chunk)},`).join('\n')}\n  ].join(''),`
})
writeFileSync(new URL('plugin/hooks/ui/arena-art-data.ts', root), `// Generated by node scripts/arena-art.ts from art/arenas/*.png; local data, never a fetched resource.\n// Standard base64 in short data-only chunks; join preserves the exact source PNG bytes.\nimport type { Family } from '../core/types.ts'\n\nexport const ARENA_PNG: Readonly<Record<Family, string>> = {\n${entries.join('\n')}\n}\n`)
